import type { Metadata } from "next"
import { TrapDripzCatalog } from "./trapdripz-catalog"

const siteUrl = "https://glitchstudios.io"
const trapDripzLogo = "/trapdripz/trapdripz-logo.png"
const trapDripzLogoAbsolute = `${siteUrl}${trapDripzLogo}`

export const metadata: Metadata = {
  metadataBase: new URL(siteUrl),
  title: "TrapDripz Sneaker & Streetwear Catalog | Glitch Studios",
  description: "A mobile-first TrapDripz resale storefront with verified photo sets, clean asks, designer filters, sizing, and trusted source notes.",
  alternates: {
    canonical: "/trapdripz",
  },
  openGraph: {
    type: "website",
    url: `${siteUrl}/trapdripz`,
    siteName: "Glitch Studios",
    title: "TrapDripz Catalog",
    description: "Verified sneaker and streetwear listings. Clean asks. Photo-first inventory.",
    images: [
      {
        url: trapDripzLogoAbsolute,
        width: 1024,
        height: 1024,
        alt: "TrapDripz logo",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "TrapDripz Catalog",
    description: "Verified sneaker and streetwear listings by Glitch Studios.",
    images: [trapDripzLogoAbsolute],
  },
}

const products = [
  {
    id: "af1-puerto-rico",
    name: "Nike Air Force 1 Low CMFT ‘Puerto Rico’",
    shortName: "AF1 Low CMFT ‘Puerto Rico’",
    designer: "Nike",
    brand: "Nike",
    category: "Sneakers",
    itemType: "Low-top sneaker",
    ask: "$220",
    askValue: 220,
    sku: "579941-100",
    color: "White / Game Royal / University Red",
    size: "US 10 on box photo; inventory says US 9.5 — verify before listing",
    sizeFilters: ["US 9.5", "US 10"],
    condition: "Brand new",
    confidence: "High — box/style code visible in set.",
    verification: "Verified set",
    note: "Size conflict needs confirmation before final buyer handoff.",
    market: "Trusted pages found on StockX/GOAT. Live market numbers were not published because scrape access was blocked; no fake comps.",
    featuredRank: 1,
    addedAt: "2026-08-13",
    sources: [
      ["StockX", "https://stockx.com/nike-air-force-1-low-cmft-puerto-rico"],
      ["GOAT", "https://www.goat.com/sneakers/air-force-1-puerto-rico-579941-100"],
      ["Flight Club", "https://www.flightclub.com/catalogsearch/result/?q=579941-100"],
    ],
    images: ["img_3a2afd2bc8c1.jpg", "img_81058f0ab912.jpg", "img_efd20bdf3cff.jpg", "img_d58357ac5e11.jpg", "img_f481a20edd4c.jpg"],
  },
  {
    id: "af1-rayguns",
    name: "Nike Air Force 1 ’07 LV8 ‘Rayguns’ / Dark Sulfur",
    shortName: "AF1 ’07 LV8 ‘Rayguns’",
    designer: "Nike",
    brand: "Nike",
    category: "Sneakers",
    itemType: "Low-top sneaker",
    ask: "$170",
    askValue: 170,
    sku: "CZ0337-700",
    color: "Black / University Gold / Team Orange-style palette",
    size: "US 9.5 per inventory",
    sizeFilters: ["US 9.5"],
    condition: "Brand new",
    confidence: "Medium-high — box label visible: AIR FORCE 1 ’07 LV8, CZ0337-700.",
    verification: "Box label seen",
    note: "Exact resale-site display name should be confirmed before publishing external market range.",
    market: "Trusted resale search links included. No clean live price result was available during this run.",
    featuredRank: 2,
    addedAt: "2026-08-13",
    sources: [
      ["StockX", "https://stockx.com/search?s=CZ0337-700"],
      ["GOAT", "https://www.goat.com/search?query=CZ0337-700"],
      ["Flight Club", "https://www.flightclub.com/catalogsearch/result/?q=CZ0337-700"],
    ],
    images: ["img_87069facafb5.jpg", "img_80ffcb4834a6.jpg", "img_6be137163037.jpg", "img_41d4daaec1c8.jpg", "img_fee81da90a73.jpg"],
  },
  {
    id: "af1-chinatown-lotus",
    name: "Nike Air Force 1 ’07 PRM ‘San Francisco Chinatown Lotus Flower’",
    shortName: "AF1 PRM ‘Chinatown Lotus’",
    designer: "Nike",
    brand: "Nike",
    category: "Sneakers",
    itemType: "Low-top sneaker",
    ask: "$190",
    askValue: 190,
    sku: "Needs style-code confirmation",
    color: "White / Pink with lotus/floral translucent outsole detail",
    size: "US 9.5 per inventory",
    sizeFilters: ["US 9.5"],
    condition: "Brand new",
    confidence: "Medium — visual match + inventory name; needs box/style code for final exact listing.",
    verification: "Needs SKU",
    note: "White/pink AF1 Low with lotus/floral detailing. Confirm SKU before buyer-facing final copy.",
    market: "No external market range published until confirmed on trusted resale pages.",
    featuredRank: 3,
    addedAt: "2026-08-13",
    sources: [
      ["StockX", "https://stockx.com/search?s=Air%20Force%201%20San%20Francisco%20Chinatown%20Lotus%20Flower"],
      ["GOAT", "https://www.goat.com/search?query=Air%20Force%201%20San%20Francisco%20Chinatown%20Lotus%20Flower"],
      ["Flight Club", "https://www.flightclub.com/catalogsearch/result/?q=Air%20Force%201%20San%20Francisco%20Chinatown%20Lotus%20Flower"],
    ],
    images: ["img_32661d65bd44.jpg", "img_9140711eddef.jpg", "img_4c7c3843670f.jpg"],
  },
  {
    id: "aj5-se-craft-light-orewood-candidate",
    name: "Air Jordan 5 SE Craft ‘Light Orewood Brown’ — needs size/SKU confirmation",
    shortName: "AJ5 SE Craft ‘Light Orewood’",
    designer: "Jordan",
    brand: "Jordan",
    category: "Sneakers",
    itemType: "High-top basketball sneaker",
    ask: "DM",
    askValue: 0,
    sku: "Needs box label / inner tag confirmation",
    color: "Light Orewood Brown / Safety Orange / Flat Pewter-style palette",
    size: "Size not visible in current photos",
    sizeFilters: ["Needs size"],
    condition: "Brand new per seller",
    confidence: "Medium — visual match to AJ5 SE Craft Light Orewood Brown family; no readable box label/style code in this photo set.",
    verification: "Needs SKU",
    note: "Beige/grey suede/nubuck Jordan 5-style pair with orange lining, lace locks, white midsole, smoky translucent outsole, and heel Jumpman. Add readable box label or inner tag before final buyer handoff.",
    market: "Trusted resale search links included. Live comps pending manual check; no fake price range published.",
    featuredRank: -4,
    addedAt: "2026-08-16",
    sources: [
      ["StockX", "https://stockx.com/search?s=Air%20Jordan%205%20SE%20Craft%20Light%20Orewood%20Brown"],
      ["GOAT", "https://www.goat.com/search?query=Air%20Jordan%205%20SE%20Craft%20Light%20Orewood%20Brown"],
      ["Flight Club", "https://www.flightclub.com/catalogsearch/result/?q=Air%20Jordan%205%20SE%20Craft%20Light%20Orewood%20Brown"],
    ],
    images: ["img_14f02d0661bb.jpg", "img_ffdb5dacfeda.jpg", "img_038d3c67a2bf.jpg", "img_003c1bb4c5db.jpg", "img_bb0da3ddcaf3.jpg", "img_4f61fc0e2e5b.jpg", "img_764e57262801.jpg"],
  },
  {
    id: "aj3-retro-cardinal-red-ct8532-126",
    name: "Air Jordan 3 Retro ‘Cardinal Red’",
    shortName: "AJ3 Retro ‘Cardinal Red’",
    designer: "Jordan",
    brand: "Jordan",
    category: "Sneakers",
    itemType: "Mid-top basketball sneaker",
    ask: "DM",
    askValue: 0,
    sku: "CT8532-126",
    color: "White / Light Curry / Cardinal Red",
    size: "US 9.5 / UK 8.5 / EUR 43 / CM 27.5 / BR 41",
    sizeFilters: ["US 9.5"],
    condition: "Brand new per seller",
    confidence: "High — box label visible: AIR JORDAN 3 RETRO, CT8532-126, White/Light Curry-Cardinal Red.",
    verification: "Box label seen",
    note: "Clean white tumbled leather AJ3 with Cardinal Red lining/midsole accents, Light Curry eyelets, and grey elephant print. Box shows light lid/corner wear in photos.",
    market: "Trusted resale search links included. Live comps pending manual check; no fake price range published.",
    featuredRank: -3,
    addedAt: "2026-08-16",
    sources: [
      ["StockX", "https://stockx.com/search?s=CT8532-126"],
      ["GOAT", "https://www.goat.com/search?query=CT8532-126"],
      ["Flight Club", "https://www.flightclub.com/catalogsearch/result/?q=CT8532-126"],
    ],
    images: ["img_f2234c663469.jpg", "img_b4dcd04818e4.jpg", "img_45776f78cd85.jpg", "img_74a538b79f05.jpg", "img_aaa4a40c758b.jpg", "img_0c9b7e18ecc6.jpg"],
  },
  {
    id: "aj3-retro-se-fire-red-ck5692-600",
    name: "Air Jordan 3 Retro SE ‘Fire Red / Unite’",
    shortName: "AJ3 Retro SE ‘Fire Red’",
    designer: "Jordan",
    brand: "Jordan",
    category: "Sneakers",
    itemType: "Mid-top basketball sneaker",
    ask: "DM",
    askValue: 0,
    sku: "CK5692-600",
    color: "Fire Red / Fire Red / Cement Grey",
    size: "US 9.5 / UK 8.5 / EUR 43 / CM 27.5 / BR 41",
    sizeFilters: ["US 9.5"],
    condition: "Brand new per seller",
    confidence: "High — box label visible: AIR JORDAN 3 RETRO SE, CK5692-600, Fire Red/Fire Red-Cement Grey.",
    verification: "Box label seen",
    note: "Red leather AJ3 SE with black laces, grey perforated collar, elephant-print toe/heel overlays, Nike Air heel branding, and red insole branding. Box is visibly damaged/frayed around front flap and corners.",
    market: "Trusted resale search links included. Live comps pending manual check; no fake price range published.",
    featuredRank: -2,
    addedAt: "2026-08-16",
    sources: [
      ["StockX", "https://stockx.com/search?s=CK5692-600"],
      ["GOAT", "https://www.goat.com/search?query=CK5692-600"],
      ["Flight Club", "https://www.flightclub.com/catalogsearch/result/?q=CK5692-600"],
    ],
    images: ["img_036f8ff197a3.jpg", "img_65d2d688addc.jpg", "img_38cffcd2d639.jpg", "img_7d3f93a40a19.jpg", "img_795ba8913f6d.jpg", "img_d6673173218a.jpg", "img_2f4a6a4b3296.jpg", "img_016f3baf6b94.jpg"],
  },
  {
    id: "christian-louboutin-high-top-multicolor-candidate",
    name: "Christian Louboutin Multicolor High-Top Sneaker — needs label confirmation",
    shortName: "Louboutin Multicolor High-Top",
    designer: "Christian Louboutin",
    brand: "Christian Louboutin",
    category: "Designer sneakers",
    itemType: "High-top designer sneaker",
    ask: "DM",
    askValue: 0,
    sku: "Needs box label / sole sticker confirmation",
    color: "White mesh / yellow-gold trim / navy heel / iridescent black toe / red sole",
    size: "Label appears to show 40, but needs clear confirmation",
    sizeFilters: ["EU 40", "Needs size"],
    condition: "Brand new per seller",
    confidence: "Medium — Christian Louboutin branding/box/red sole visible; exact model name and size need a clearer label shot.",
    verification: "Needs label",
    note: "Mixed-material high-top on brown Louboutin Paris box with signature red outsole, white mesh side panels, yellow-gold overlays, navy heel, iridescent toe cap, and white laces. Box shows wear/creases.",
    market: "Trusted resale search links included. Exact model/label confirmation needed before publishing comps.",
    featuredRank: -1,
    addedAt: "2026-08-16",
    sources: [
      ["StockX", "https://stockx.com/search?s=Christian%20Louboutin%20multicolor%20high%20top%20sneaker"],
      ["GOAT", "https://www.goat.com/search?query=Christian%20Louboutin%20multicolor%20high%20top%20sneaker"],
      ["Flight Club", "https://www.flightclub.com/catalogsearch/result/?q=Christian%20Louboutin%20multicolor%20high%20top%20sneaker"],
    ],
    images: ["img_b0b616cbd085.jpg", "img_4ed5c2d3d8da.jpg", "img_74a05636c073.jpg", "img_9e8f93b1bb87.jpg"],
  },
  {
    id: "aj1-mid-se-chile-red-dc7294-600",
    name: "Air Jordan 1 Mid SE ‘Chile Red / White / Pollen’",
    shortName: "AJ1 Mid SE ‘Chile Red’",
    designer: "Jordan",
    brand: "Jordan",
    category: "Sneakers",
    itemType: "Mid-top lifestyle basketball sneaker",
    ask: "DM",
    askValue: 0,
    sku: "DC7294-600",
    color: "Chile Red / Metallic Gold / White",
    size: "US 9.5 / UK 8.5 / EUR 43 / CM 27.5 / BR 41",
    sizeFilters: ["US 9.5"],
    condition: "Brand new per seller",
    confidence: "High — box label visible: AIR JORDAN 1 MID SE, DC7294-600, Chile Red/Metallic Gold.",
    verification: "Box label seen",
    note: "Red-and-white AJ1 Mid SE with glossy Chile Red overlays, metallic/gold Pollen Swoosh, red laces, patterned collar detailing, and black outsole. Box shows minor label/flap wear.",
    market: "Trusted resale search links included. Live comps pending manual check; no fake price range published.",
    featuredRank: 0,
    addedAt: "2026-08-16",
    sources: [
      ["StockX", "https://stockx.com/search?s=DC7294-600"],
      ["GOAT", "https://www.goat.com/search?query=DC7294-600"],
      ["Flight Club", "https://www.flightclub.com/catalogsearch/result/?q=DC7294-600"],
    ],
    images: ["img_6abf883d06fd.jpg", "img_9d42b04cfefe.jpg", "img_14de78b22581.jpg", "img_f42145c781b5.jpg", "img_d1beb8c63a34.jpg", "img_cba9b0047767.jpg", "img_3f6802159c80.jpg"],
  },
  {
    id: "aj6-retro-toro-bravo-candidate",
    name: "Air Jordan 6 Retro ‘Toro Bravo’ — needs unobscured label confirmation",
    shortName: "AJ6 Retro ‘Toro Bravo’",
    designer: "Jordan",
    brand: "Jordan",
    category: "Sneakers",
    itemType: "High-top basketball sneaker",
    ask: "DM",
    askValue: 0,
    sku: "CT8529-600 candidate; box label mostly obscured",
    color: "Varsity Red / Black / White / Icy translucent outsole",
    size: "US 9.5 / UK 8.5 / EUR 43 / CM 27.5 visible on damaged box label",
    sizeFilters: ["US 9.5"],
    condition: "Brand new per seller",
    confidence: "Medium-high — visuals match AJ6 Retro Toro Bravo; damaged box label exposes size but blocks model/SKU text.",
    verification: "Needs clear label",
    note: "Bright red suede/nubuck AJ6 with black tongue/heel details, visible Air unit, white midsole sections, and icy translucent outsole. Box front is heavily torn/bent over the label, so keep SKU as candidate until Trap sends a clear tag/label shot.",
    market: "Trusted resale search links included. Live comps pending manual check; no fake price range published.",
    featuredRank: 3,
    addedAt: "2026-08-16",
    sources: [
      ["StockX", "https://stockx.com/search?s=CT8529-600"],
      ["GOAT", "https://www.goat.com/search?query=CT8529-600"],
      ["Flight Club", "https://www.flightclub.com/catalogsearch/result/?q=CT8529-600"],
    ],
    images: ["img_76e1620e9e76.jpg", "img_895e403d84fe.jpg", "img_a1b962a4aa32.jpg", "img_92644dac36f8.jpg", "img_d7648b0d9147.jpg", "img_51ef582930bc.jpg", "img_1877ed96f14e.jpg"],
  },
  {
    id: "aj13-retro-black-true-red-dj5982-060",
    name: "Air Jordan 13 Retro ‘Black / True Red / White’",
    shortName: "AJ13 Retro ‘Black Red’",
    designer: "Jordan",
    brand: "Jordan",
    category: "Sneakers",
    itemType: "Mid-top basketball sneaker",
    ask: "DM",
    askValue: 0,
    sku: "DJ5982-060",
    color: "Black / True Red / White",
    size: "US 10 / UK 9 / EUR 44 / CM 28 / BR 42",
    sizeFilters: ["US 10"],
    condition: "Brand new per seller",
    confidence: "High — box label visible: AIR JORDAN 13 RETRO, DJ5982-060, Black/True Red-White.",
    verification: "Box label seen",
    note: "Black/white AJ13 with True Red accents, hologram ankle badge, quilted side panels, white laces, and panther-paw midsole pods. Box shows visible dents/scuffs/creased corners.",
    market: "Trusted resale search links included. Live comps pending manual check; no fake price range published.",
    featuredRank: 1,
    addedAt: "2026-08-16",
    sources: [
      ["StockX", "https://stockx.com/search?s=DJ5982-060"],
      ["GOAT", "https://www.goat.com/search?query=DJ5982-060"],
      ["Flight Club", "https://www.flightclub.com/catalogsearch/result/?q=DJ5982-060"],
    ],
    images: ["img_c0f17eee2183.jpg", "img_7464e2a2d93f.jpg", "img_3ef6e758b7a7.jpg", "img_8b133448d18a.jpg", "img_d2689a09f1bf.jpg", "img_c6723b69ab8a.jpg", "img_92c2094823e8.jpg"],
  },
  {
    id: "aj5-retro-aqua-dd0587-047",
    name: "Air Jordan 5 Retro ‘Aqua’",
    shortName: "AJ5 Retro ‘Aqua’",
    designer: "Jordan",
    brand: "Jordan",
    category: "Sneakers",
    itemType: "High-top basketball sneaker",
    ask: "DM",
    askValue: 0,
    sku: "DD0587-047",
    color: "Black / Aquatone / Taxi",
    size: "US 9.5 / UK 8.5 / EUR 43 / CM 27.5",
    sizeFilters: ["US 9.5"],
    condition: "Brand new per seller",
    confidence: "High — box label visible with DD0587-047 and US 9.5; visuals match AJ5 Aqua black/aqua/yellow palette.",
    verification: "Box label seen",
    note: "Black nubuck AJ5 with aqua Jumpman/tongue lining/outsole accents, translucent side mesh and lace locks, reflective tongue, and yellow-orange shark-tooth midsole details. Box shows front-tab wear.",
    market: "Trusted resale search links included. Live comps pending manual check; no fake price range published.",
    featuredRank: 2,
    addedAt: "2026-08-16",
    sources: [
      ["StockX", "https://stockx.com/search?s=DD0587-047"],
      ["GOAT", "https://www.goat.com/search?query=DD0587-047"],
      ["Flight Club", "https://www.flightclub.com/catalogsearch/result/?q=DD0587-047"],
    ],
    images: ["img_35be48f221b4.jpg", "img_ccf40f41deb4.jpg", "img_8ff181de78a8.jpg", "img_4d8205bda6dc.jpg", "img_9a5e0a4b18ab.jpg", "img_8bb579de2216.jpg", "img_8b6b1e574120.jpg"],
  },
  {
    id: "black-jordan-candidate",
    name: "Black Metallic Air Jordan Candidate — needs verification",
    shortName: "Black Metallic Jordan Candidate",
    designer: "Jordan",
    brand: "Jordan",
    category: "Sneakers",
    itemType: "Basketball sneaker",
    ask: "$150",
    askValue: 150,
    sku: "Unknown",
    color: "Black / Metallic Silver with icy/yellowed outsole sections",
    size: "US 9.5 per inventory",
    sizeFilters: ["US 9.5"],
    condition: "Brand new with yellowing frost / verify",
    confidence: "Low-medium — resembles a black metallic Jordan 6-family shoe, but exact model is not proven.",
    verification: "Needs ID",
    note: "Needs box label or close tag photos. Exact model intentionally not guessed.",
    market: "No market price published because exact shoe is not verified.",
    featuredRank: 4,
    addedAt: "2026-08-13",
    sources: [
      ["StockX", "https://stockx.com/search?s=Air%20Jordan%206%20Black%20Metallic%20Silver%20Low%20Chrome"],
      ["GOAT", "https://www.goat.com/search?query=Air%20Jordan%206%20Black%20Metallic%20Silver%20Low%20Chrome"],
      ["Flight Club", "https://www.flightclub.com/catalogsearch/result/?q=Air%20Jordan%206%20Black%20Metallic%20Silver%20Low%20Chrome"],
    ],
    images: ["img_dac1d62d8f08.jpg", "img_f2d0388c0c9c.jpg"],
  },
]

export default function TrapDripzPage() {
  return <TrapDripzCatalog logoSrc={trapDripzLogo} products={products} />
}


